scriptencoding utf-8
set encoding=utf-8
set nocompatible              " 去除VI一致性,必须
filetype off                  " 必须
set termguicolors

" backspace over everything in insert mode
" set backspace=indent,eol,start

" Force to use system self-owned python interpreter
" Since python@2 and python had been installed in /usr/local/, the system's
" vim cannot distinguish between these python executors and system's python
" interpreter.
let $PATH="/usr/bin:" . $PATH

" 显示行号
set number

" set lcs=space:␣
" set list

" tab键=2个空格
set ts=2
set expandtab

" A good line to memorize:
"  :set et sts=4 sw=4 ts=4

"   et  = expandtab (spaces instead of tabs)
"   ts  = tabstop (the number of spaces that a tab equates to)
"   sw  = shiftwidth (the number of spaces to use when indenting
"         -- or de-indenting -- a line)
"   sts = softtabstop (the number of spaces to use when expanding tabs)


" YAML file indentaion setting
autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab

" shell file indentaion setting
autocmd FileType sh setlocal ts=2 sts=2 sw=4 expandtab


" 开启语法高亮功能
syntax enable
" 允许用指定语法高亮配色方案替换默认方案
syntax on

" 使用 NERDTree 插件查看工程文件。设置快捷键，速记：file list
nmap <Leader>fl :NERDTreeToggle<CR>
" 设置NERDTree子窗口宽度
let NERDTreeWinSize=32
" 设置NERDTree子窗口位置
let NERDTreeWinPos="left"
" 显示隐藏文件
let NERDTreeShowHidden=1
" NERDTree 子窗口中不显示冗余帮助信息
let NERDTreeMinimalUI=1
" 删除文件时自动删除文件对应 buffer
let NERDTreeAutoDeleteBuffer=1

" NERDTress File highlighting
function! NERDTreeHighlightFile(extension, fg, bg, guifg, guibg)
 exec 'autocmd filetype nerdtree highlight ' . a:extension .' ctermbg='. a:bg .' ctermfg='. a:fg .' guibg='. a:guibg .' guifg='. a:guifg
 exec 'autocmd filetype nerdtree syn match ' . a:extension .' #^\s\+.*'. a:extension .'$#'
endfunction


" call NERDTreeHighlightFile('jade', 'green', 'none', 'green', '#151515')
" call NERDTreeHighlightFile('ini', 172, 'none', '#ff9b6d', '#151515')
" call NERDTreeHighlightFile('md', 228, 'none', '#3366FF', '#151515')
" call NERDTreeHighlightFile('yml', 172, 'none', '#ff9b6d', '#151515')
" call NERDTreeHighlightFile('yaml', 172, 'none', '#ff9b6d', '#151515')
" call NERDTreeHighlightFile('config', 172, 'none', '#ff9b6d', '#151515')
" call NERDTreeHighlightFile('conf', 172, 'none', 172, '#151515')
" call NERDTreeHighlightFile('json', 172, 'none', 172, '#151515')
" call NERDTreeHighlightFile('html', 172, 'none', 172, '#151515')
" call NERDTreeHighlightFile('styl', 'cyan', 'none', 'cyan', '#151515')
" call NERDTreeHighlightFile('css', 'cyan', 'none', 'cyan', '#151515')
" call NERDTreeHighlightFile('coffee', 'Red', 'none', 'red', '#151515')
" call NERDTreeHighlightFile('js', 'Red', 'none', '#ffa500', '#151515')
" call NERDTreeHighlightFile('php', 'Magenta', 'none', '#ff00ff', '#151515')
call NERDTreeHighlightFile('jade', 'green', 'none', 'green', '#151515')
call NERDTreeHighlightFile('ini', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('md', 'blue', 'none', '#3366FF', '#151515')
call NERDTreeHighlightFile('yml', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('config', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('conf', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('json', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('html', 'yellow', 'none', 'yellow', '#151515')
call NERDTreeHighlightFile('styl', 'cyan', 'none', 'cyan', '#151515')
call NERDTreeHighlightFile('css', 'cyan', 'none', 'cyan', '#151515')
call NERDTreeHighlightFile('coffee', 'Red', 'none', 'red', '#151515')
call NERDTreeHighlightFile('js', 'Red', 'none', '#ffa500', '#151515')
call NERDTreeHighlightFile('php', 'Magenta', 'none', '#ff00ff', '#151515')


" height ligth cusor
" set bg=dark
set cursorline
" highlight CursorLine cterm=none ctermbg=239
highlight Visual cterm=bold ctermbg=245 ctermfg=NONE


" Change color settings in YouCompleteMe
highlight Pmenu ctermfg=15 ctermbg=0 guifg=#ffffff guibg=#ff8700

" set cursorcolumn

" 设置包括vundle和初始化相关的runtime path
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" 另一种选择, 指定一个vundle安装插件的路径
"call vundle#begin('~/some/path/here')

" 让vundle管理插件版本,必须
Plugin 'VundleVim/Vundle.vim'

" Folder tree
Plugin 'scrooloose/nerdtree'

" Underline the word under the cursor
Plugin 'itchyny/vim-cursorword'

" A code-completion engine for vim
Plugin 'Valloric/YouCompleteMe'

" A git wrapper so awesome, it should be illegal
" ref: https://vimawesome.com/plugin/fugitive-vim
Plugin 'tpope/vim-fugitive'

" 你的所有插件需要在下面这行之前
call vundle#end()            " 必须
filetype plugin indent on    " 必须 加载vim自带和插件相应的语法和文件类型相关脚本
" 忽视插件改变缩进,可以使用以下替代:
"filetype plugin on
"
" 简要帮助文档
" :PluginList       - 列出所有已配置的插件
" :PluginInstall    - 安装插件,追加 `!` 用以更新或使用 :PluginUpdate
" :PluginSearch foo - 搜索 foo ; 追加 `!` 清除本地缓存
" :PluginClean      - 清除未使用插件,需要确认; 追加 `!` 自动批准移除未使用插件
"
" 查阅 :h vundle 获取更多细节和wiki以及FAQ
" 将你自己对非插件片段放在这行之后

